# config/dev.yaml
data_sources:
  basketball_reference:
    url: "https://www.basketball-reference.com"
    rate_limit: 20

storage:
  local_path: "data"
  azure_storage:
    container_name: "basketball-data"

api:
  host: "0.0.0.0"
  port: 8000
  debug: true